name: ship_qarte
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  list_tile_switch: ^0.0.2
  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0
  backdrop: ^0.4.7
  carousel_pro: ^1.0.0
  flutter_swiper: ^1.1.6
  image_picker: ^0.7.4
  firebase_auth: ^1.4.1
  firebase_core: ^1.6.0
  google_sign_in: ^5.0.7
  cloud_firestore: ^2.5.1
  firebase_storage: ^8.1.0
  provider: ^4.3.3
  flutter_staggered_grid_view: ^0.4.0
  badges: ^2.0.1
  shared_preferences: ^2.0.7
  flutter_lints: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/emptycart.png
    - assets/images/carousel1.png
    - assets/images/carousel2.jpg
    - assets/images/carousel3.jpg
    - assets/images/carousel4.png
    - assets/images/addidas.jpg
    - assets/images/apple.jpg
    - assets/images/Dell.jpg
    - assets/images/h&m.jpg
    - assets/images/nike.jpg
    - assets/images/samsung.jpg
    - assets/images/Huawei.jpg
    - assets/images/CatBeauty.jpg
    - assets/images/CatClothes.jpg
    - assets/images/CatFurniture.jpg
    - assets/images/CatLaptops.png
    - assets/images/CatPhones.png
    - assets/images/CatShoes.jpg
    - assets/images/CatWatches.jpg
    - assets/images/empty-wishlist.png
    - assets/images/person_setting.png
    - assets/images/person.png
